# -*- coding: utf-8 -*-
"""P8_analyse_GBR_troquetbar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jVepqWseBuJany5eSMigUtj1zqm4dkK_
"""

import pandas as pd 
import re 
import numpy as np
#import pillow 
pd.set_option('display.max_colwidth', None)
from google.colab import files
files.upload()
#data = pd.read_csv('https://drive.google.com/file/d/1ZzgRhOeD8hcQbbBM9H6DwaJsphae8kCE/view?usp=sharing')

data = pd.read_csv('newest_gm_reviews.csv') 
data.head(4)

data1 = data.caption
data1

# transformation de la colonne en text pour les prochains traitement. 
data2 = data1.str.cat(sep=' ').replace(' .','.') 
text = data2 
text

# We lowercase the text to avoid having to deal with uppercase and capitalized words
text = text.lower()

"""Transforming a text into a list of words is called tokenization, and each word is a token.

A simple way to tokenize is to split the text over whitespaces with  text.split(' ')  .

"""

#lister les noms qui composent le text.
#calcul du nombre de fois que des noms qui apparaissent dans le texte.  
from collections import Counter 
word_list = text.split() 
word_counts = Counter(word_list) 

for w in word_counts.most_common():
    print(f"{w[0]}:  \t{w[1]} ")

# import the wordcloud library
from wordcloud import WordCloud
# Instantiate a new wordcloud.
wordcloud = WordCloud(
        random_state = 8,
        normalize_plurals = False,
        width = 600, 
        height= 300,
        max_words = 300,
        stopwords = [])

# Apply the wordcloud to the text.
wordcloud.generate(text)

import matplotlib.pyplot as plt
# create a figure
fig, ax = plt.subplots(1,1, figsize = (20,20))
# add interpolation = bilinear to smooth things out
plt.imshow(wordcloud, interpolation='bilinear')
# and remove the axis
plt.axis("off")

print(list(WordCloud().stopwords))

# transform the text into a list of words
words_list = text.split(' ')
# define the list of words you want to remove from the text
stopwords = ['','et','not','on',' ','i','we', 'it', ',','(original)','…','google)','(translated','(Translated by Google)','the', 'of', 'and', 'is','to','in','a','from','by','that', 'with', 'this', 'as', 'an', 'are','its', 'at', 'for']
# use a python list comprehension to remove the stopwords from words_list
words_without_stopwords = [ word for word in words_list if word not in stopwords ]

Counter(words_without_stopwords).most_common()

from wordcloud import WordCloud
# Instantiate a new wordcloud.
wordcloud = WordCloud(
        random_state = 8,
        normalize_plurals = False,
        width = 800, 
        height= 800,
        max_words = 300,
        stopwords = [])

# Transform the list of words back into a string 
text_without_stopwords  = ' '.join(words_without_stopwords)

# Apply the wordcloud to the text.
wordcloud.generate(text_without_stopwords)

# And plot
import matplotlib.pyplot as plt
fig, ax = plt.subplots(1,1, figsize = (20,20))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off") 
plt.savefig("wordcloud.png") 

from google.colab import files
plt.savefig("wordcloud.png")
files.download("wordcloud.png")

from google.colab import files
plt.savefig("wordcloud.png")
files.download("wordcloud.png")

!pip install nltk

import nltk
nltk.download('popular')

from nltk.tokenize import WordPunctTokenizer
from collections import Counter

from nltk.tokenize import WordPunctTokenizer

text = text_without_stopwords 

tokens = WordPunctTokenizer().tokenize(text)
print(Counter(tokens).most_common(40))

"""Some words are better taken together: New York, Happy end, Wall street, Linear regression etc ... . When tokenizing we want to consider all possible adjacent pairs of words in the text. We can do this with the NLTK ngrams function"""

from nltk import ngrams

text = text_without_stopwords.lower()

# Tokenize
tokens = WordPunctTokenizer().tokenize(text)
unigrams = WordPunctTokenizer().tokenize(text)
# bigrams 
bigrams = [w for w in  ngrams(tokens,n=2)]
print(bigrams)

print()
bigrams = ['_'.join(bg) for bg in bigrams]
print(bigrams)

"""# and for trigrams """

trigrams = ['_'.join(w) for w in  ngrams(tokens,n=3)]

print(trigrams)

text = text.lower()
unigrams = WordPunctTokenizer().tokenize(text)
bigrams = ['_'.join(w) for w in  ngrams(unigrams,n=2)]
trigrams = ['_'.join(w) for w in  ngrams(unigrams,n=3)]

tokens = unigrams + bigrams + trigrams

print(f"we have a total of {len(tokens)} tokens, including: \n- {len(unigrams)} unigrams \n- {len(bigrams)} bigrams \n- {len(trigrams)} trigrams. ")

Counter(tokens).most_common(100)

df = data
df

df1 = df[['username','rating','caption']]
df2 = df1.rename(columns={"caption": "text"})

df2.info()

df2.dropna()

import spacy
nlp = spacy.load("en_core_web_sm")

#Add a couple of punctuation signs with multi charaters as stopwords to the nlp spacy mode
nlp.Defaults.stop_words.add("`,")
nlp.Defaults.stop_words.add("``")
nlp.Defaults.stop_words.add("(Translated")
nlp.Defaults.stop_words.add("by")
nlp.Defaults.stop_words.add("Google)")
nlp.Defaults.stop_words.add("(Original)")
nlp.Defaults.stop_words.add("Translated")
nlp.Defaults.stop_words.add("Google")
nlp.Defaults.stop_words.add("Original")
nlp.Defaults.stop_words.add("translate")
nlp.Defaults.stop_words.add("Google")

def preprocess(text):
    doc = nlp(text)
    tokens = [token.lemma_ for token in doc if not (token.is_stop or token.is_punct)]
    return ' '.join(tokens)

text = '''These are the good times; Leave your cares behind'''
print(preprocess(text))

#df2['processed_text'] = df2.text.apply(lambda txt : preprocess(txt))
#df2['processed_text']
df2['text'].str.len()
df2['text'].fillna('', inplace=True)

df2['processed_text'] = df2.text.apply(lambda txt : preprocess(txt))
#df2['processed_text']

df2

